### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by pietrobraione** [star-finder/jpf-costar#1]
https://github.com/star-finder/jpf-costar/blob/b3f4d4893019a42b6c3f50e4294fd3ab6f2b5f88/src/main/costar/CoStarListener.java#L89

The method starlib.jpf.testsuites.TestGenerator.generateTests() does not exist, at least not in the current version of starlib, and consequently jpf-costar does not compile.

**Comment by qsphan** [comment]
@pietrobraione , please clone from the `artifact` branch, it is the stable branch that we used to submit the artifact.
