### ISSUE TITLE
Build fails because of lack of Plexil example

### ISSUE THREAD

**Issue by pietrobraione** [star-finder/jpf-costar#3]
Since the source (or binary) of the Plexil example is missing, the ant build is failing when trying to compile src/examples/plexil/parser/Driver.java and src/examples/plexil/parser2/Driver.java.

**Comment by qsphan** [comment]
Thanks for reporting the issue. In the mean time, could you try obtaining a docker image from docker hub. There is instruction in the Appendix 4 of this technical report:
https://arxiv.org/pdf/1907.05637.pdf

**Comment by qsphan** [comment]
@pietrobraione , please clone the `artifact` branch, it's the branch that we used to submit the artifact.
